url: http://hackers-of-umass.github.io

# Members
members:
    - name: Ty-Lucas Kelley
      url: http://www.tylucaskelley.com
    - name: Adonis Familia
    - name: Anthony Gentile
    - name: Kevin Gurney
    - name: Dylan Fischler
      url: http://dylanfischler.com/
    - name: Anthony Chan
    - name: Vincent Nguyen
    - name: Nathan Fuller
      url: http://people.umass.edu/nefuller/
    - name: Sahil Chaturvedi
    - name: Vincent Lou
    - name: Jack Valinsky
    - name: Aaron Weiss
      url: http://aaronweiss.us/
    - name: Will Shepherd
    - name: Taylor Smaldone
    - name: Leo Lin
      url: http://www.leoxlin.com/
    - name: Evan Michelson
    - name: Anh Duc Bui
    - name: Dan Bergevin
    - name: Bob Ambrose
    - name: Derek Dobosz
    - name: Kaitlin Menzie
    - name: Adish Rai
    - name: Hoang Nguyen
    - name: Steven Pham
    - name: Chris Brissette
    - name: Catherine Feldman
    - name: Corey Waple
    - name: Liam Albright-Wint
    - name: Michaela Michi Shtilman Minkin
    - name: Jake Bernstein
    - name: Alex Chan
    - name: Brendan Ross
    - name: Aidan Wolf
    - name: Dave Fontenot
    - name: Tri Nguyen
    - name: Alex Rafael Bran Perez
    - name: Thai Nguyen
    - name: Liam Kelly
    - name: Santiago De La Torre
    - name: Dailton Rabelo
    - name: Corey Haigh
    - name: Connor Demille
    - name: Dakota Morse
    - name: Minh Tran
    - name: Cara Magliozzi
    - name: Levis Agaba
    - name: Neal Merkl
    - name: Eva Snyder
    - name: Batkhuyag Batsaikhan
    - name: Tejbir Singh
    - name: Christopher D. Scott
    - name: Omid Meh
    - name: Tommy Nguyen
    - name: Appa Salvi
    - name: Adrian Poveda
    - name: Freddy Q. Nguyen
    - name: Josh Gallant
    - name: Blaine Stillerman
    - name: Jackson Crook
    - name: Supriya Kankure
    - name: Noel Recchia
    - name: Kostis Gourgoulias
    - name: Wei Xie
    - name: Patrick Neal
    - name: Quang T Le
    - name: Uday Savaria
    - name: Michael Amirault
    - name: Steve Jones
    - name: Shawn Sowersby
    - name: Daniel Lipeles
    - name: Seph Solimini
    - name: Kristina Mahoney
    - name: Billy Chen
    - name: Rich Mpanga
    - name: Ocho Cho
    - name: Richard Yan
    - name: Emi Yu
    - name: Zainab Aqdas
    - name: Andrew Raleigh
    - name: Shravan Nayak
    - name: Congzhe Zhang
    - name: Craig Moore
    - name: Tashee Na
    - name: James Curry
    - name: Grant George
    - name: Derek Duoba
    - name: Joe Geneva
    - name: Carl Senecal
    - name: Lucas Meira
    - name: Chenyao  Xue
    - name: Doug Gandle
    - name: Jordan Gyaltsen
    - name: Chenhao Huang
    - name: Grant Park
    - name: Sri Tangirala
    - name: Corwin Burdick
    - name: Line Yin
    - name: Giovanna Diaz
    - name: Bradley Swift
    - name: Anubhab Haldar
    - name: Noah Green
    - name: Jake Geryk
    - name: Herbert Perks III
    - name: Aysha Mehjabeen
    - name: F Stephen Quaratiello
    - name: Richard Rosario
    - name: Vincent Lee
    - name: Tom Mc
    - name: Ed Fennessey
    - name: LÃª Thu Trang
    - name: Michael Gaiss
    - name: Mike Vartanian

# Site settings
title: Hackers of UMass
email: hackersofumass@gmail.com
description: "We're the hackers, builders, makers, and innovators of UMass Amherst."

# Colors
color:
  primary: ff6e00
  secondary: ff8600
  secondary-dark: 452411

# Font stack
font:
    logo: "'Shadows Into Light', cursive"
    text: "'Merriweather', sans-serif"
    accent: "'Lato', sans-serif"

# Social networks
social:
  - title: facebook
    url: https://facebook.com/groups/hackersofumass
  - title: github
    url: https://github.com/hackers-of-umass
  - title: slack
    url: https://umassacm.slack.com/messages/hackers-of-umass
  - title: envelope
    url: mailto:hackersofumass@gmail.com

# Build settings
markdown: kramdown
permalink: pretty
